language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .[test]

script: pytest --cov twyla.kubedeploy --cov-report term-missing --verbose
after_script:
  - pip install codecov
  - codecov
